//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class AidRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AidRequest()
        {
            this.RequestedItems = new HashSet<RequestedItem>();
        }
    
        public int RequestId { get; set; }
        public int UserId { get; set; }
        public string RequestTitle { get; set; }
        public string Description { get; set; }
        public string UrgencyLevel { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> IsPosted { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestedItem> RequestedItems { get; set; }
    }
}
