//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributionOrderItem
    {
        public int DistributionOrderItemId { get; set; }
        public int DistributionOrderId { get; set; }
        public int ItemId { get; set; }
        public decimal Quantity { get; set; }
        public string Unit { get; set; }
    
        public virtual DistributionOrder DistributionOrder { get; set; }
        public virtual ItemMaster ItemMaster { get; set; }
    }
}
