//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentId { get; set; }
        public string BeneficiaryName { get; set; }
        public string Purpose { get; set; }
        public string Items { get; set; }
        public string CNIC { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> GeneratedDate { get; set; }
    }
}
