//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donation()
        {
            this.DonationItems = new HashSet<DonationItem>();
        }
    
        public int DonationId { get; set; }
        public int DonorId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> DonationDate { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonationItem> DonationItems { get; set; }
        public virtual User User { get; set; }
        public virtual Donor Donor { get; set; }
    }
}
