//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestedItem
    {
        public int RequestedItemId { get; set; }
        public int RequestId { get; set; }
        public string ItemName { get; set; }
        public decimal Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<int> ItemRequestCount { get; set; }
    
        public virtual AidRequest AidRequest { get; set; }
    }
}
